/* ARRAYS SÃO CONJUNTOS DE DADOS QUE ARMAZENAM VALORES DE UM ÚNICO TIPO. 
   EXISTEM DUAS FORMAS DE SE DECLARAR UM ARRAY:
      let array1 :[u32; 5] = [0, 2, 4, 6, 1]; 
   - PRIMEIRO DECLARAMOS O TIPO DE DADOS QUE ESSE ARRAY VAI RECEBER E DEPOIS 
   O NÚMERO DE ELEMENTOS DESSE ARRAY.
      let array2 = ['a', 'b', 'c', 'd', 'e'];
   - PODEMOS DECLARAR UM ARRAY SEM INFORMAR NEM OS TIPOS DE DADOS PERTENCENTES AO ARRAY, 
   ASSIM COMO NÃO PRECISAMOS INFORMAR O NÚMERO DE ELEMENTOS DO ARRAY. O COMPILADOR SE ENCARREGA
   DE FAZER ESSE TRABALHO PARA NÓS!

   PARA IMPRIMIR UM ARRAY NA TELA PRECISAMOS COLOCAR O NOME DO ARRAY SEGUIDO PELO SEU ÍNDICE.
   EX:  println!(" {} ", array2[0]);
*/

fn main() {

    let array1 :[u32; 5] = [0, 2, 4, 6, 1];
    let array2 = ['a', 'b', 'c', 'd', 'e'];

    println!(" {} {} {} ", array2[1], array1[1], array1[3]);
}
