/* REGRAS PARA CONSTANTES:
   - DEVEM SER DECLARADAS COM LETRAS MAIÚSCULAS
   - NÃO PODEM COMEÇAR COM NÚMEROS
   - PODEM CONTER:
     - NÚMEROS
     - UNDERSCORE ( _ )
   - INFORMAR O TIPO DE DADO DA CONSTANTE
*/

const GLOBAL_CONST :i64 = 1_000_000;

fn main() {

    const LOCAL_CONST :i64 = 2_000_000;

    println!("GLOBAL_CONST = {} \nLOCAL_CONST = {}", GLOBAL_CONST, LOCAL_CONST);
}
