/* PARA CRIAÇÃO DE FUNÇÕES DEVEMOS DIGITAR A PALAVRA RESERVADA fn SEGUIDA DO NOME DA FUNÇÃO.
   DEPOIS DO NOME, ABRIMOS PARÊNTESES E PODEREMOS COLOCAR UM OU MAIS 
   PARÂMETROS DENTRO, COM SEUS RESPECTIVOS TIPOS DE DADOS, CLARO.
   DEPOIS DEVEMOS DAR UM ESPAÇO E DIGITAR `->` SEM AS ASPAS. 
   APÓS O SINAL, DEVEMOS COLOCAR O TIPO DE DADO REFERENTE AO RETORNO DA FUNÇÃO.
   DEPOIS ABRIMOS AS CHAVES `{}` E DENTRO DELAS DEVEMOS COLOCAR O RETORNO. 
   EX:  fn dobro(x:i32) -> i32{
            return 2*f;
        }
*/

fn dobro(x :i64) -> f64{
    return (2*x) as f64;
}


fn main(){
    println!("O dobro de 5 é {:.2}", dobro(5));
}
